version: '3.8'
services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=rosdistant_example
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci